name = "homyo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./src/userInterface/cloudflareWorker/index.ts"

# [[d1_databases]]
# TODO: Add a database configuration here
